apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::310565147479:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-O4JKRO3F0DTH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      - system:nodes
      rolearn: arn:aws:iam::310565147479:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-25T05:52:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1376"
  uid: 814ae0a1-ae2f-4ff7-b4eb-e5368563bb15
